[build.environment]
SECRETS_SCAN_OMIT_KEYS = "VITE_GITLAB_USER_ID,VITE_GITLAB_PROJECT_ID"

[build]
   publish = "dist"
   command = "vitepress build docs"


[context.deploy-preview]
  command = "vitepress build"
